### ISSUE TITLE
Instalation

### ISSUE THREAD

**Issue by maoricl** [MatusKysel/EMVemulator#11]
Hello I cannot install the app on my Huawei Mate 1 Pro can u help me?

**Comment by MatusKysel** [comment]
Can you give me more details?

**Comment by maoricl** [comment]
BLA-L09
EMUI 9.1.0
COMPILED 9.1.0.325(C45E7R1P12)
ANDROID 9

**Comment by MatusKysel** [comment]
I mean more about "cannot install", what kind of error you are getting or something like that

**Comment by maoricl** [comment]
i download all the folder straight to the phone the apk and the other folder all in the same, run the APK but just open and dont even recognize the NFC or read, just stay on the main screen of the app, maybe imdoing it wrong....

**Comment by PdxTrader18** [comment]
I need to contact you in privet regarding a  business appoutonity, emial me 
ceo@renitngzone-sa.com
waiting for you

**Comment by maoricl** [comment]
> I need to contact you in privet regarding a  business appoutonity, emial me 
> ceo@renitngzone-sa.com
> waiting for you 

Your host is not working

**Comment by PdxTrader18** [comment]
sorry @maoricl
 I meant @MatusKysel
dhtrader18@gmail.com 
is this code copy righted by any chance ?
