### ISSUE TITLE
Can it be used as opensource *Pay system?

### ISSUE THREAD

**Issue by leadrig** [MatusKysel/EMVemulator#12]
Hello. All we know about all these systems like Google Pay, Apple Pay.., etc.
Can your app be used as opensource alternative to it?

**Comment by MatusKysel** [comment]
I do not think so, if you check README, there warning 

> WARNING! This application might destroy your credit card (MasterCard only) after ~ 66 successful attacks.*

**Comment by leadrig** [comment]
@MatusKysel but what if I will copy my card once and then just use that emulation feature? From README:
`Data collection is completed and your phone is ready for emulating your card`

**Comment by MatusKysel** [comment]
First of all this attack si 4y old, so I think most of card issuers already implemented counter measures against this attack.
Secondly this attack has some restictions e.g. this card clone can be used only to perform limited number of transactions and this collcted data are valid only until you do not perform any transaction with card itself. More here https://github.com/MatusKysel/EMVemulator/blob/master/Cloning%20Credit%20Cards%20A%20combined%20pre-play-Roland.pdf
