### ISSUE TITLE
Card issue

### ISSUE THREAD

**Issue by DAVID9SE** [MatusKysel/EMVemulator#6]
The card did not work after using the app.I dont think the problem was in the ATC.I tested the app few times (3-5) on my card then i tried to pay with the phone.......TRANSACTION DENIED than with the card.....TRANSACTION DENIED. Card damage is not the issue i was just wondering why ? Is it connected with the fact that i loaded it with the app and did not used it? Thanks for your reply and for this awesom concept app.Sorry for my english.

**Comment by MatusKysel** [comment]
Hi there,
It's quite difficult to know for sure why your transaction have been denied, especially without any logs or debug outputs. But I think, that your card issuer probably detect this kind of transaction and automatically blocks card, so it can not be used fraudulently.

**Comment by DAVID9SE** [comment]
After 1 day the card is working again but the emulated card is still not working.I think there is a protection.But it is weird because the card is a mastercard.

**Comment by MatusKysel** [comment]
It is not weird at all, there is huge difference between card brand such as MasterCard and card issuer (or card processing center) e.g. FirstData. You can find more here [What is difference between card issuer and card network?](https://www.quora.com/What-is-difference-between-card-issuer-and-card-network) and here [What is a Credit Card Issuer?](https://www.thebalance.com/credit-card-issuer-959984)

**Comment by DAVID9SE** [comment]
Thanks a lot for your help and explanation.
