### ISSUE TITLE
Question 

### ISSUE THREAD

**Issue by eastinterface** [MatusKysel/EMVemulator#9]
Im running a samsung S7 edge and ive downloades the app to test an emulated card on a reader 
The card gets copied but when i place phone to reader it does nothing 
Even when i put app in background 

Any ideas on what the problem could be?
Thanks

**Comment by MatusKysel** [comment]
Hi, without any logs it is hard to say what went wrong. Unfortunately, I do not have equipment to test your setup, so I guess I can not help you.

**Comment by Litha150** [comment]
Hi 

Hope you are doing well. My name is Litha Matala and I'm from South Africa I've developed a wearable contactless payment device and I was finding ways to test it out but have been coming to a dead end, until I came across M. Roland's video on cloning credit cards. So I was hoping to download the apk file and test it out using my OWN debit/credit card, but the only problem is I don't have a POS terminal system to test it out on. My question is can I test it out on a real stores POS terminal system? Or will that get me in big trouble? Thanks 

Regards

**Comment by MatusKysel** [comment]
Hi Litha,
you can try this software https://www.terminalsimulator.com/ and use it with normal card reader. I would not recommend to use real POS terminal.

**Comment by Litha150** [comment]
Okay. Thank you for rapid response. The reason why I ask this is because I will be presenting this idea to a bank in the upcoming week. So my concern was, if they wanted to see a demonstration how would I show them. If you don't mind me asking what happens when a cloned card is read on a real POS terminal?

**Comment by MatusKysel** [comment]
First of all it it not legal at all, but it depends if and how is your card issuer is handling this issue.

**Comment by Litha150** [comment]
OK. Thank I got, I will not be testing it out on Real POS terminals. But is it legal for me to use this apk file to clone my OWN debit card to my NFC Ring to use at a presentation which I will be doing at a Bank next week?

**Comment by eastinterface** [comment]
@matusKysel 

Could you point me in the right direction by informing me which phone would work best with this app?
 Thanks

**Comment by MatusKysel** [comment]
> @MatusKysel
> 
> Could you point me in the right direction by informing me which phone would work best with this app?
> Thanks

Hi, sorry for delay, but I am quite busy right now. So I have try it with my Samsung S9 and terminal simulator, that I have mention in comment before and everything worked for me.

**Comment by MatusKysel** [comment]
> OK. Thank I got, I will not be testing it out on Real POS terminals. But is it legal for me to use this apk file to clone my OWN debit card to my NFC Ring to use at a presentation which I will be doing at a Bank next week?

I am not a lawyer you need to find out by yourself

**Comment by eastinterface** [comment]
Thanks @matuskysel

**Comment by eastinterface** [comment]
@Litha150
Id be glad to test your EMV replay device if you have one

**Comment by thechacal** [comment]
> > @MatusKysel
> > Could you point me in the right direction by informing me which phone would work best with this app?
> > Thanks
> 
> Hi, sorry for delay, but I am quite busy right now. So I have try it with my Samsung S9 and terminal simulator, that I have mention in comment before and everything worked for me.

Hello,

This app works with any cell phone with nfc technologies?

**Comment by thechacal** [comment]
Another things:

1) This app works only with mastercard?
2) When the app completed the data collecting, it showed ( screenshots in github ): 

Type of card; 
Card Number; 
Card Expiration; 

Can I put this data Instead reading and write on the blank card?

**Comment by MatusKysel** [comment]
closed due to inactivity
